import type { AppState, Contact } from "@/lib/api/types";

export const defaultAppState: AppState = {
  user: null,
  onboardingComplete: false,
  platform: {
    currentRole: "workspace_owner",
    workspaces: [
      {
        id: "ws-1",
        name: "Aarav Fashion",
        plan: "Growth",
        billingStatus: "Active",
        activeContacts: 12450,
        monthlySpend: 18200,
        ownerName: "Rohan Mehta",
        ownerEmail: "rohan@aaravfashion.in",
        resellerId: "res-1",
        resellerName: "Scale Partners",
      },
      {
        id: "ws-2",
        name: "Urban Glow Clinic",
        plan: "Starter",
        billingStatus: "Trial",
        activeContacts: 3180,
        monthlySpend: 4600,
        ownerName: "Nidhi Arora",
        ownerEmail: "nidhi@urbanglow.in",
        resellerId: "res-2",
        resellerName: "Growth Orbit",
      },
      {
        id: "ws-3",
        name: "KitchenKart D2C",
        plan: "Enterprise",
        billingStatus: "Past Due",
        activeContacts: 28400,
        monthlySpend: 51200,
        ownerName: "Karan Bedi",
        ownerEmail: "karan@kitchenkart.in",
        resellerId: null,
        resellerName: null,
      },
    ],
    resellers: [
      {
        id: "res-1",
        name: "Utkarsh Makwana",
        email: "reseller@wabiz.app",
        companyName: "Scale Partners",
        tier: "Gold",
        status: "Active",
        commissionRate: 18,
        clientsManaged: 6,
        monthlyRecurringRevenue: 74000,
        monthlyPayout: 13320,
        referralCode: "SCALE-UTK",
        pipelineValue: 128000,
      },
      {
        id: "res-2",
        name: "Sanya Kapoor",
        email: "partner@wabiz.app",
        companyName: "Growth Orbit",
        tier: "Silver",
        status: "Pending",
        commissionRate: 12,
        clientsManaged: 2,
        monthlyRecurringRevenue: 22000,
        monthlyPayout: 2640,
        referralCode: "GORBIT-SK",
        pipelineValue: 34000,
      },
      {
        id: "res-3",
        name: "Arjun Desai",
        email: "arjun@channelhub.in",
        companyName: "ChannelHub",
        tier: "Platinum",
        status: "Active",
        commissionRate: 22,
        clientsManaged: 11,
        monthlyRecurringRevenue: 146000,
        monthlyPayout: 32120,
        referralCode: "CH-ARJUN",
        pipelineValue: 210000,
      },
    ],
    resellerProfile: {
      id: "res-1",
      name: "Utkarsh Makwana",
      email: "reseller@wabiz.app",
      companyName: "Scale Partners",
      tier: "Gold",
      status: "Active",
      commissionRate: 18,
      clientsManaged: 6,
      monthlyRecurringRevenue: 74000,
      monthlyPayout: 13320,
      referralCode: "SCALE-UTK",
      pipelineValue: 128000,
    },
    alerts: [
      {
        id: "pa-1",
        severity: "warning",
        title: "1 workspace is past due",
        description: "KitchenKart D2C needs billing follow-up before next renewal cycle.",
      },
      {
        id: "pa-2",
        severity: "info",
        title: "Pending reseller onboarding",
        description: "Growth Orbit is waiting for contract approval and payout activation.",
      },
    ],
  },
  walletBalance: 4250,
  totalSpent: 12780,
  messagesSent: 25560,
  contacts: [
    { id: "c1", name: "Rahul Sharma", phone: "+91 98765 43210", tags: ["VIP", "Shopify"] },
    { id: "c2", name: "Priya Patel", phone: "+91 87654 32109", tags: ["New"] },
    { id: "c3", name: "Amit Kumar", phone: "+91 76543 21098", tags: ["Returning"] },
    { id: "c4", name: "Sneha Gupta", phone: "+91 65432 10987", tags: ["VIP", "D2C"] },
    { id: "c5", name: "Vikram Singh", phone: "+91 54321 09876", tags: ["Shopify"] },
    { id: "c6", name: "Anjali Reddy", phone: "+91 43210 98765", tags: ["New", "D2C"] },
  ],
  templates: [
    {
      id: "t1",
      name: "Order Confirmation",
      category: "Utility",
      status: "Approved",
      language: "English",
      body: "Hi {{1}}, your order #{{2}} has been confirmed! Track here: {{3}}",
      preview: "Hi {{1}}, your order #{{2}} has been confirmed! Track here: {{3}}",
    },
    {
      id: "t2",
      name: "Diwali Sale Offer",
      category: "Marketing",
      status: "Approved",
      language: "English",
      body: "Diwali Sale is LIVE! Get up to {{1}}% off on all products. Shop now: {{2}}",
      preview: "Diwali Sale is LIVE! Get up to {{1}}% off on all products. Shop now: {{2}}",
    },
    {
      id: "t3",
      name: "Cart Reminder",
      category: "Marketing",
      status: "Pending",
      language: "English",
      body: "Hey {{1}}, you left items in your cart! Complete your purchase before they sell out.",
      preview: "Hey {{1}}, you left items in your cart! Complete your purchase before they sell out.",
    },
    {
      id: "t4",
      name: "Shipping Update",
      category: "Utility",
      status: "Approved",
      language: "Hindi",
      body: "Hi {{1}}, your order has been shipped! Delivery by {{2}}. Track: {{3}}",
      preview: "Hi {{1}}, your order has been shipped! Delivery by {{2}}. Track: {{3}}",
    },
    {
      id: "t5",
      name: "Feedback Request",
      category: "Marketing",
      status: "Rejected",
      language: "English",
      body: "Hi {{1}}, how was your experience with us? Rate us here: {{2}}",
      preview: "Hi {{1}}, how was your experience with us? Rate us here: {{2}}",
    },
  ],
  campaigns: [
    {
      id: "cmp-1",
      name: "Diwali Sale Blast",
      templateId: "t2",
      contactIds: ["c1", "c2", "c3", "c4"],
      status: "Delivered",
      date: "2026-03-20",
      estimatedCost: 625,
      spent: 625,
      sent: 4,
      delivered: 4,
      read: 3,
    },
    {
      id: "cmp-2",
      name: "New Arrival Alert",
      templateId: "t1",
      contactIds: ["c1", "c5"],
      status: "Sending",
      date: "2026-03-21",
      estimatedCost: 430,
      spent: 430,
      sent: 2,
      delivered: 1,
      read: 0,
    },
    {
      id: "cmp-3",
      name: "Weekly Newsletter",
      templateId: "t4",
      contactIds: ["c1", "c2", "c3", "c4", "c5", "c6"],
      status: "Scheduled",
      date: "2026-03-25",
      estimatedCost: 1600,
      spent: 0,
      sent: 0,
      delivered: 0,
      read: 0,
    },
  ],
  transactions: [
    { id: "txn-1", type: "credit", desc: "Wallet Recharge", amount: 2000, date: "2026-03-20", balance: 4250 },
    { id: "txn-2", type: "debit", desc: "Diwali Sale Blast", amount: -625, date: "2026-03-20", balance: 2250 },
    { id: "txn-3", type: "debit", desc: "Order Confirmation", amount: -1050, date: "2026-03-18", balance: 2875 },
    { id: "txn-4", type: "credit", desc: "Wallet Recharge", amount: 3000, date: "2026-03-16", balance: 3925 },
  ],
  whatsApp: {
    connected: false,
    connectionStatus: "pending",
    businessVerificationStatus: "unverified",
    accountReviewStatus: "pending_review",
    obaStatus: "not_applied",
    metaBusinessId: "",
    metaBusinessPortfolioId: "",
    wabaId: "",
    phoneNumberId: "",
    displayPhoneNumber: "",
    verifiedName: "",
    businessPortfolio: "",
    businessName: "",
    authorizationStatus: "missing",
    authorizationExpiresAt: null,
  },
  conversations: [
    {
      id: "conv-1",
      contactId: "c1",
      phone: "+91 98765 43210",
      displayName: "Rahul Sharma",
      status: "Open",
      source: "WhatsApp Inbound",
      assignedTo: "Sales Team",
      lastMessagePreview: "Can you share the latest price for the premium package?",
      lastMessageAt: "2026-03-23T10:30:00.000Z",
      unreadCount: 2,
    },
    {
      id: "conv-2",
      contactId: "c4",
      phone: "+91 65432 10987",
      displayName: "Sneha Gupta",
      status: "Pending",
      source: "Meta Ads",
      assignedTo: "Growth Desk",
      lastMessagePreview: "Interested in a WhatsApp automation demo.",
      lastMessageAt: "2026-03-23T08:00:00.000Z",
      unreadCount: 0,
    },
  ],
  conversationMessages: [
    {
      id: "msg-1",
      conversationId: "conv-1",
      direction: "Inbound",
      messageType: "text",
      body: "Can you share the latest price for the premium package?",
      status: "received",
      sentAt: "2026-03-23T10:30:00.000Z",
    },
    {
      id: "msg-2",
      conversationId: "conv-1",
      direction: "Outbound",
      messageType: "text",
      body: "Absolutely. I can send the pricing breakdown and onboarding plan.",
      status: "sent",
      sentAt: "2026-03-23T10:34:00.000Z",
    },
    {
      id: "msg-3",
      conversationId: "conv-2",
      direction: "Inbound",
      messageType: "text",
      body: "Interested in a WhatsApp automation demo.",
      status: "received",
      sentAt: "2026-03-23T08:00:00.000Z",
    },
  ],
  conversationNotes: [
    {
      id: "note-1",
      conversationId: "conv-1",
      body: "Pricing-sensitive lead. Share premium plan breakdown before offering discount.",
      authorName: "Sales Team",
      createdAt: "2026-03-23T10:36:00.000Z",
    },
    {
      id: "note-2",
      conversationId: "conv-2",
      body: "Requested a live automation walkthrough after seeing the Meta lead ad.",
      authorName: "Growth Desk",
      createdAt: "2026-03-23T08:12:00.000Z",
    },
  ],
  conversationEvents: [
    {
      id: "evt-1",
      conversationId: "conv-1",
      eventType: "assignment_updated",
      summary: "Conversation assigned to Sales Team.",
      actorName: "Utkarsh",
      createdAt: "2026-03-23T10:35:00.000Z",
    },
    {
      id: "evt-2",
      conversationId: "conv-2",
      eventType: "status_updated",
      summary: "Conversation moved to Pending follow-up.",
      actorName: "Growth Desk",
      createdAt: "2026-03-23T08:15:00.000Z",
    },
  ],
  failedSendLogs: [
    {
      id: "fail-1",
      channel: "campaign",
      targetType: "contact",
      targetId: "c2",
      destination: "+91 87654 32109",
      templateName: "Diwali Sale Offer",
      messageBody: null,
      errorMessage: "Meta API returned a temporary delivery error.",
      status: "failed",
      createdAt: "2026-03-24T09:20:00.000Z",
    },
    {
      id: "fail-2",
      channel: "reply",
      targetType: "conversation",
      targetId: "conv-1",
      destination: "+91 98765 43210",
      templateName: null,
      messageBody: "Absolutely. Sharing the quote now.",
      errorMessage: "Meta authorization expired for this workspace.",
      status: "failed",
      createdAt: "2026-03-24T10:05:00.000Z",
    },
  ],
  operationalLogs: [
    {
      id: "op-1",
      eventType: "campaign_send_failed",
      level: "error",
      summary: "Diwali Sale campaign failed for one recipient and needs retry.",
      createdAt: "2026-03-24T09:20:00.000Z",
    },
    {
      id: "op-2",
      eventType: "webhook_received",
      level: "info",
      summary: "WhatsApp webhook processed successfully for connected phone number.",
      createdAt: "2026-03-24T08:55:00.000Z",
    },
  ],
  leads: [
    {
      id: "lead-1",
      contactId: "c4",
      conversationId: "conv-2",
      fullName: "Sneha Gupta",
      phone: "+91 65432 10987",
      email: "sneha@example.com",
      status: "New",
      source: "Meta Ads",
      sourceLabel: "Spring Offer • Page 10827364 • Ad 8827191 • Form 441928",
      assignedTo: "Growth Desk",
      notes: "Lead captured automatically from Meta Lead Ads webhook.\nPage ID: 10827364\nAd ID: 8827191\nForm ID: 441928",
      createdAt: "2026-03-23T07:55:00.000Z",
    },
    {
      id: "lead-2",
      contactId: "c1",
      conversationId: "conv-1",
      fullName: "Rahul Sharma",
      phone: "+91 98765 43210",
      email: "rahul@example.com",
      status: "Qualified",
      source: "WhatsApp Inbound",
      sourceLabel: "Organic WhatsApp inquiry",
      assignedTo: "Sales Team",
      notes: "Asked for pricing and onboarding support.",
      createdAt: "2026-03-22T14:00:00.000Z",
    },
  ],
  automations: [
    {
      id: "auto-1",
      type: "auto_reply_first_inbound",
      name: "First inbound auto-reply",
      enabled: true,
      config: {
        message: "Hi {{contact.name}}, thanks for reaching out. Our team has received your message and will reply shortly.",
      },
      updatedAt: "2026-03-24T09:10:00.000Z",
    },
    {
      id: "auto-2",
      type: "auto_assign_new_lead",
      name: "Auto-assign new leads",
      enabled: true,
      config: {
        ownerName: "Growth Desk",
      },
      updatedAt: "2026-03-24T09:12:00.000Z",
    },
    {
      id: "auto-3",
      type: "no_reply_reminder",
      name: "No-reply follow-up reminder",
      enabled: true,
      config: {
        reminderHours: 4,
        ownerName: "Sales Team",
      },
      updatedAt: "2026-03-24T09:14:00.000Z",
    },
    {
      id: "auto-4",
      type: "follow_up_after_contacted",
      name: "Post-contacted follow-up",
      enabled: false,
      config: {
        message: "Hi {{contact.name}}, thanks for speaking with us. I am sharing the next step here so we can keep the conversation moving.",
      },
      updatedAt: "2026-03-24T09:16:00.000Z",
    },
  ],
  automationEvents: [
    {
      id: "ae-1",
      ruleType: "auto_reply_first_inbound",
      conversationId: "conv-1",
      leadId: "lead-2",
      status: "triggered",
      summary: "Auto-reply sent after first inbound message from Rahul Sharma.",
      createdAt: "2026-03-24T07:45:00.000Z",
    },
    {
      id: "ae-2",
      ruleType: "auto_assign_new_lead",
      conversationId: "conv-2",
      leadId: "lead-1",
      status: "triggered",
      summary: "New lead assigned to Growth Desk.",
      createdAt: "2026-03-24T07:46:00.000Z",
    },
  ],
  recentActivity: [
    {
      id: "act-1",
      title: "Campaign delivered",
      subtitle: "Diwali Sale Blast reached 1,250 customers",
      timestamp: "2 hours ago",
    },
    {
      id: "act-2",
      title: "Wallet recharged",
      subtitle: "Added Rs 2,000 to the prepaid wallet",
      timestamp: "5 hours ago",
    },
    {
      id: "act-3",
      title: "Template approved",
      subtitle: "Order Confirmation is now ready to use",
      timestamp: "Yesterday",
    },
  ],
};

export function sampleUploadedContacts(): Contact[] {
  return [
    { id: crypto.randomUUID(), name: "Kunal Mehta", phone: "+91 99887 77665", tags: ["CSV", "Shopify"] },
    { id: crypto.randomUUID(), name: "Neha Kapoor", phone: "+91 90909 80808", tags: ["CSV", "VIP"] },
    { id: crypto.randomUUID(), name: "Ritesh Jain", phone: "+91 93456 78123", tags: ["CSV", "Retail"] },
  ];
}
